# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tr_55_dialog_base.ui'
#
# Created: Fri Jul 10 07:24:20 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Tr55DialogBase(object):
    def setupUi(self, Tr55DialogBase):
        Tr55DialogBase.setObjectName(_fromUtf8("Tr55DialogBase"))
        Tr55DialogBase.resize(400, 300)
        self.tabWidget = QtGui.QTabWidget(Tr55DialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.button_box = QtGui.QDialogButtonBox(self.tab)
        self.button_box.setGeometry(QtCore.QRect(10, 220, 331, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.line = QtGui.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(10, 66, 351, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 95, 351, 111))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(18)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.BasinsLabel = QtGui.QLabel(self.layoutWidget)
        self.BasinsLabel.setObjectName(_fromUtf8("BasinsLabel"))
        self.gridLayout_3.addWidget(self.BasinsLabel, 0, 0, 1, 1)
        self.BasinsCombo = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BasinsCombo.sizePolicy().hasHeightForWidth())
        self.BasinsCombo.setSizePolicy(sizePolicy)
        self.BasinsCombo.setObjectName(_fromUtf8("BasinsCombo"))
        self.gridLayout_3.addWidget(self.BasinsCombo, 0, 1, 1, 1)
        self.CoverTypeLabel = QtGui.QLabel(self.layoutWidget)
        self.CoverTypeLabel.setObjectName(_fromUtf8("CoverTypeLabel"))
        self.gridLayout_3.addWidget(self.CoverTypeLabel, 1, 0, 1, 1)
        self.CoverCombo = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CoverCombo.sizePolicy().hasHeightForWidth())
        self.CoverCombo.setSizePolicy(sizePolicy)
        self.CoverCombo.setObjectName(_fromUtf8("CoverCombo"))
        self.gridLayout_3.addWidget(self.CoverCombo, 1, 1, 1, 1)
        self.HSGLabel = QtGui.QLabel(self.layoutWidget)
        self.HSGLabel.setObjectName(_fromUtf8("HSGLabel"))
        self.gridLayout_3.addWidget(self.HSGLabel, 2, 0, 1, 1)
        self.HSGCombo = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HSGCombo.sizePolicy().hasHeightForWidth())
        self.HSGCombo.setSizePolicy(sizePolicy)
        self.HSGCombo.setObjectName(_fromUtf8("HSGCombo"))
        self.gridLayout_3.addWidget(self.HSGCombo, 2, 1, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 17, 351, 41))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setVerticalSpacing(18)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.DEMLabel = QtGui.QLabel(self.layoutWidget1)
        self.DEMLabel.setObjectName(_fromUtf8("DEMLabel"))
        self.gridLayout_4.addWidget(self.DEMLabel, 0, 0, 1, 1)
        self.DEMCombo = QtGui.QComboBox(self.layoutWidget1)
        self.DEMCombo.setObjectName(_fromUtf8("DEMCombo"))
        self.gridLayout_4.addWidget(self.DEMCombo, 0, 1, 1, 1)
        self.WatershedsButton = QtGui.QPushButton(self.layoutWidget1)
        self.WatershedsButton.setObjectName(_fromUtf8("WatershedsButton"))
        self.gridLayout_4.addWidget(self.WatershedsButton, 0, 2, 1, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(130, 18, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(125, 130, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.layoutWidget2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 40, 351, 71))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setVerticalSpacing(18)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.SaveLabel = QtGui.QLabel(self.layoutWidget2)
        self.SaveLabel.setObjectName(_fromUtf8("SaveLabel"))
        self.gridLayout.addWidget(self.SaveLabel, 0, 0, 1, 1)
        self.DirectoryLine = QtGui.QLineEdit(self.layoutWidget2)
        self.DirectoryLine.setObjectName(_fromUtf8("DirectoryLine"))
        self.gridLayout.addWidget(self.DirectoryLine, 0, 1, 1, 1)
        self.DirectoryButton = QtGui.QToolButton(self.layoutWidget2)
        self.DirectoryButton.setObjectName(_fromUtf8("DirectoryButton"))
        self.gridLayout.addWidget(self.DirectoryButton, 0, 2, 1, 1)
        self.ftpLabel = QtGui.QLabel(self.layoutWidget2)
        self.ftpLabel.setObjectName(_fromUtf8("ftpLabel"))
        self.gridLayout.addWidget(self.ftpLabel, 1, 0, 1, 1)
        self.ftpLine = QtGui.QLineEdit(self.layoutWidget2)
        self.ftpLine.setObjectName(_fromUtf8("ftpLine"))
        self.gridLayout.addWidget(self.ftpLine, 1, 1, 1, 1)
        self.noaaButton = QtGui.QToolButton(self.layoutWidget2)
        self.noaaButton.setObjectName(_fromUtf8("noaaButton"))
        self.gridLayout.addWidget(self.noaaButton, 1, 2, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(self.tab_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 156, 351, 60))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setVerticalSpacing(18)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.BasinsLabel_2 = QtGui.QLabel(self.layoutWidget3)
        self.BasinsLabel_2.setObjectName(_fromUtf8("BasinsLabel_2"))
        self.gridLayout_2.addWidget(self.BasinsLabel_2, 0, 0, 1, 1)
        self.ca_methodCombo = QtGui.QComboBox(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ca_methodCombo.sizePolicy().hasHeightForWidth())
        self.ca_methodCombo.setSizePolicy(sizePolicy)
        self.ca_methodCombo.setObjectName(_fromUtf8("ca_methodCombo"))
        self.gridLayout_2.addWidget(self.ca_methodCombo, 0, 1, 1, 1)
        self.BasinsLabel_3 = QtGui.QLabel(self.layoutWidget3)
        self.BasinsLabel_3.setObjectName(_fromUtf8("BasinsLabel_3"))
        self.gridLayout_2.addWidget(self.BasinsLabel_3, 1, 0, 1, 1)
        self.ch_initLine = QtGui.QLineEdit(self.layoutWidget3)
        self.ch_initLine.setObjectName(_fromUtf8("ch_initLine"))
        self.gridLayout_2.addWidget(self.ch_initLine, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.helpText = QtGui.QTextBrowser(self.tab_3)
        self.helpText.setGeometry(QtCore.QRect(10, 10, 351, 241))
        self.helpText.setSource(QtCore.QUrl(_fromUtf8("file:///C:/Users/Link Liar/.qgis2/python/plugins/Tr55/dialog_help.txt")))
        self.helpText.setObjectName(_fromUtf8("helpText"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))

        self.retranslateUi(Tr55DialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), Tr55DialogBase.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), Tr55DialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(Tr55DialogBase)

    def retranslateUi(self, Tr55DialogBase):
        Tr55DialogBase.setWindowTitle(_translate("Tr55DialogBase", "TR55", None))
        self.BasinsLabel.setText(_translate("Tr55DialogBase", "Watershed Basins:", None))
        self.CoverTypeLabel.setText(_translate("Tr55DialogBase", "Land Cover Type:", None))
        self.HSGLabel.setText(_translate("Tr55DialogBase", "HSG:", None))
        self.DEMLabel.setText(_translate("Tr55DialogBase", "DEM:", None))
        self.WatershedsButton.setText(_translate("Tr55DialogBase", "Delineate Watersheds", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Tr55DialogBase", "Main", None))
        self.label_2.setText(_translate("Tr55DialogBase", "General options", None))
        self.label_3.setText(_translate("Tr55DialogBase", "Watershed options", None))
        self.SaveLabel.setText(_translate("Tr55DialogBase", "Save file:", None))
        self.DirectoryButton.setText(_translate("Tr55DialogBase", "   ...  ", None))
        self.ftpLabel.setText(_translate("Tr55DialogBase", "FTP server:", None))
        self.noaaButton.setText(_translate("Tr55DialogBase", "NOAA", None))
        self.BasinsLabel_2.setText(_translate("Tr55DialogBase", "Catchment Area Method:", None))
        self.BasinsLabel_3.setText(_translate("Tr55DialogBase", "Ch. Network Initiation Threshold:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Tr55DialogBase", "Options", None))
        self.helpText.setHtml(_translate("Tr55DialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Tr55 plugin help. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">1) Choose DEM layer. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">2) Switch to Options tab and choose save file location </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">   * if a location isn\'t specified, the file is saved to Desktop and named &quot;Default&quot;. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">   * the folder with the analysis files is always stored in the same directory as the main file. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">   * Folder name W55p. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">3) Choose Catchment Area Method and Channel Network Initiation Threshold, or leave default. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">4) Switch back to Main tab and click Delineate Watersherds </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">5) Make the choices in the fields activated below and click OK.</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Tr55DialogBase", "Help", None))

